apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata: 
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: nsaqui4c/fibonacci_api:v1
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-clusterip
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER  
              value: postgres
            - name: PGHOST
              value: postgres-clusterip
            - name: PGDATABASE
              value:  postgres
            - name: PGPORT
              value: '5432'
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD 

